import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// Note: This file is generated by the FlutterFire CLI 
import 'firebase_options.dart'; 

void main() async {
  // Required to ensure plugin services are initialized 
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase for the specific platform 
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: Center(child: Text("Firebase Initialized"))));
  }
}